# Generated by Django 5.2.10 on 2026-01-12 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by_worker', models.BooleanField(default=False)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publish_log', to='programs.lesson')),
            ],
        ),
    ]
