# Generated by Django 5.2.10 on 2026-01-12 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.lesson')),
            ],
            options={
                'unique_together': {('lesson', 'language_code')},
            },
        ),
    ]
