# Generated by Django 5.2.10 on 2026-01-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_add_order_field_to_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
