# Generated by Django 5.2.10 on 2026-01-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='slug',
            field=models.SlugField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
